In [4]:
# 1
import numpy as np
vec = np.arange(1, 11)
print(vec)

[ 1  2  3  4  5  6  7  8  9 10]


In [24]:
# 2
import numpy as np
arr = np.zeros((3, 3), dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
# 3
import numpy as np
make_arr = np.random.randint(1, 11, (5, 5))
print(make_arr)

[[ 5  1  7  8  8]
 [10 10  5  2  5]
 [ 5  5  4  5  9]
 [ 2  2  3  4  2]
 [ 9  2  8  4  7]]


In [27]:
# 4
import numpy as np
make_arr = np.random.rand(4, 4)
print(make_arr)


[[0.75027826 0.11570231 0.68786684 0.90706709]
 [0.37528899 0.48123643 0.3331499  0.24113575]
 [0.24748981 0.38190256 0.46925775 0.87638278]
 [0.66613038 0.83209768 0.53525048 0.62176138]]


In [12]:
# 5
import numpy as np
# Створення двох одновимірних масивів
arr1 = np.random.randint(1, 11, 5)
arr2 = np.random.randint(1, 11, 5)
print(f"Масив 1: {arr1}")
print(f"Масив 2: {arr2}")

# Поелементні операції
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2

print(f"Додавання: {addition}")
print(f"Віднімання: {subtraction}")
print(f"Множення: {multiplication}")


Масив 1: [ 7  7 10 10  7]
Масив 2: [3 4 3 7 5]
Додавання: [10 11 13 17 12]
Віднімання: [4 3 7 3 2]
Множення: [21 28 30 70 35]


In [29]:
# 6
import numpy as np
vec1 = np.random.rand(7)
vec2 = np.random.rand(7)
print(f"Вектор 1: {vec1}")
print(f"Вектор 2: {vec2}")

# Знаходження скалярного добутку
scalar_product = np.dot(vec1, vec2)

print(f"Скалярний добуток: {scalar_product}")


Вектор 1: [0.51932577 0.52547649 0.45727071 0.55172385 0.19866311 0.58536478
 0.77884121]
Вектор 2: [0.35855877 0.24903004 0.80784691 0.95403129 0.97682338 0.79146599
 0.82310143]
Скалярний добуток: 2.5112551769395313


In [ ]:
# 7
# слід врахувати, що перемножувати матриці розміром 2x2 та 2x3 неможливо

In [30]:
# 8 
import numpy as np
# Створення матриц
matrix = np.random.randint(1, 11, (3, 3))
print(f"Початкова матриця:\n{matrix}")

# Знаходження оберненої матриці
try:
    inverse_matrix = np.linalg.inv(matrix)
    print(f"Обернена матриця:\n{inverse_matrix}")
except np.linalg.LinAlgError:
    print("Матриця є виродженою і не має оберненої матриці.")


Початкова матриця:
[[ 7  4  6]
 [ 8  2 10]
 [ 1  3  9]]
Обернена матриця:
[[ 0.06   0.09  -0.14 ]
 [ 0.31  -0.285  0.11 ]
 [-0.11   0.085  0.09 ]]


In [32]:
# 9
import numpy as np
# Створення матриці
matrix = np.random.rand(4, 4)
print(f"Початкова матриця:\n{matrix}\n")

# Транспонування матриці
transposed_matrix = matrix.T
print(f"Транспонована матриця:\n{transposed_matrix}")

Початкова матриця:
[[0.11343184 0.83341984 0.62026447 0.74325016]
 [0.95831135 0.60735602 0.66667884 0.60255595]
 [0.71660033 0.1097484  0.30355564 0.68482859]
 [0.49996353 0.5496687  0.95207931 0.81352193]]

Транспонована матриця:
[[0.11343184 0.95831135 0.71660033 0.49996353]
 [0.83341984 0.60735602 0.1097484  0.5496687 ]
 [0.62026447 0.66667884 0.30355564 0.95207931]
 [0.74325016 0.60255595 0.68482859 0.81352193]]


In [34]:
# 10
import numpy as np
# Створення матриці розміром 3x4
matrix = np.random.randint(1, 11, (3, 4))

# Створення вектора розміром 4
vector = np.random.randint(1, 11, 4)

print(f"Матриця:\n{matrix}\n")
print(f"Вектор:\n{vector}\n")

result = np.dot(matrix, vector)

print(f"Результат перемноження матриці на вектор:\n{result}")

Матриця:
[[2 5 6 6]
 [1 1 6 5]
 [5 1 2 3]]

Вектор:
[6 3 2 5]

Результат перемноження матриці на вектор:
[69 46 52]


In [39]:
# 11
import numpy as np
# Створення матриці розміром 2x3
matrix = np.random.rand(2, 3)

# Створення вектора розміром 3
vector = np.random.rand(3)

print(f"Матриця:\n{matrix}\n")
print(f"Вектор:\n{vector}\n")


result = np.dot(matrix, vector)
print(f"Результат перемноження матриці на вектор:\n{result}")

Матриця:
[[0.72535403 0.42368351 0.01560652]
 [0.69765683 0.04097076 0.13197154]]

Вектор:
[0.66399088 0.96861761 0.97189939]

Результат перемноження матриці на вектор:
[0.90718374 0.63118584]


In [6]:
# 12
import numpy as np
# Створення двох матриц розміром 2x2
arr1 = np.random.randint(1, 11, (2, 2))
arr2 = np.random.randint(1, 11, (2, 2))
print(f"матрицa 1: {arr1}")
print(f"матрицa 2: {arr2}")

multiplication = arr1 * arr2
print(f"Множення: {multiplication}")



матрицa 1: [[3 4]
 [5 6]]
матрицa 2: [[10  6]
 [ 6  5]]
Множення: [[30 24]
 [30 30]]


In [9]:
# 13
import numpy as np
# Створення двох матриц розміром 2x2
arr1 = np.random.randint(1, 11, (2, 2))
arr2 = np.random.randint(1, 11, (2, 2))

print(f"матрицa 1: {arr1}")
print(f"матрицa 2: {arr2}")

product = np.dot(arr1, arr2)
print(f"добуток: {product}")


матрицa 1: [[1 7]
 [7 6]]
матрицa 2: [[3 5]
 [3 5]]
добуток: [[24 40]
 [39 65]]


In [11]:
# 14
import numpy as np

# Створення матриці розміром 5x5
matrix = np.random.randint(1, 101, size=(5, 5))
print(f"Матриця:\n{matrix}\n")

# Знаходження суми елементів матриці
sum_elements = np.sum(matrix)
print(f"Сума елементів матриці: {sum_elements}")


Матриця:
[[41 59 42 15 88]
 [33 60 77 32 35]
 [78 84 40 67 64]
 [25 84 47 93 64]
 [87 34  1 30 82]]

Сума елементів матриці: 1362


In [13]:
# 15
import numpy as np

# Створення двох матриць розміром 4x4
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print(f"Матриця 1:\n{matrix1}\n")
print(f"Матриця 2:\n{matrix2}\n")

# Знаходження різниці між матрицями
difference = matrix1 - matrix2
print(f"Різниця між матрицями:\n{difference}")


Матриця 1:
[[5 2 8 1]
 [6 1 6 9]
 [9 9 6 1]
 [8 3 7 3]]

Матриця 2:
[[ 9  3  8  5]
 [ 8  5  8  7]
 [10  8  8  2]
 [ 5  9  2  8]]

Різниця між матрицями:
[[-4 -1  0 -4]
 [-2 -4 -2  2]
 [-1  1 -2 -1]
 [ 3 -6  5 -5]]


In [14]:
# 16
import numpy as np

# Створення матриці розміром 3x3
matrix = np.random.rand(3, 3)
print(f"Матриця:\n{matrix}\n")

# Знаходження вектора-стовпчика, що містить суму елементів кожного рядка матриці
sum_vector = np.sum(matrix, axis=1).reshape(-1, 1)
print(f"Вектор-стовпчик із сумами елементів рядків:\n{sum_vector}")


Матриця:
[[0.69082661 0.51087243 0.9057534 ]
 [0.57983399 0.580555   0.25786943]
 [0.5498171  0.62355919 0.76921786]]

Вектор-стовпчик із сумами елементів рядків:
[[2.10745244]
 [1.41825842]
 [1.94259415]]


In [16]:
# 17
import numpy as np

# Створення матриці розміром 3x4 з випадковими цілими числами в діапазоні від 1 до 10
matrix = np.random.randint(1, 11, (3, 4))
print(f"Початкова матриця:\n{matrix}\n")

# Створення матриці з квадратами чисел
squared_matrix = matrix ** 2
print(f"Матриця з квадратами чисел:\n{squared_matrix}")


Початкова матриця:
[[5 1 5 8]
 [1 5 2 5]
 [1 2 8 1]]

Матриця з квадратами чисел:
[[25  1 25 64]
 [ 1 25  4 25]
 [ 1  4 64  1]]


In [18]:
# 18
import numpy as np

# Створення вектора розміром 4 з випадковими цілими числами в діапазоні від 1 до 50
vector = np.random.randint(1, 51, 4)
print(f"Початковий вектор: {vector}")

# Знаходження вектора з квадратними коренями чисел
sqrt_vector = np.sqrt(vector)
print(f"Вектор з квадратними коренями: {sqrt_vector}")



Початковий вектор: [49 38  6 10]
Вектор з квадратними коренями: [7.         6.164414   2.44948974 3.16227766]
